"""
Signals module - Signal parsing and validation for trading signals.
Contains regex patterns, parsers, and validators for options and stocks.
"""

from .parser import (
    parse_option_signal,
    parse_stock_signal,
    SignalParser,
    get_default_option_pattern,
    get_default_stock_pattern,
)
from .patterns import (
    FLEXIBLE_OPT_PATTERN,
    DEFAULT_STK_PATTERN,
    create_option_regex,
    create_stock_regex,
)
from .validator import (
    validate_signal,
    is_valid_symbol,
    is_valid_strike,
    is_valid_expiry,
    is_valid_action,
    check_ticker_filter,
)
from .spy_sniper_parser import (
    is_spy_sniper_signal,
    parse_spy_sniper_signal,
    process_spy_sniper_message,
    SpySniperSignal,
    SpySniperSignalType,
    SpySniperPositionTracker,
    get_position_tracker,
    format_as_bto,
    format_as_stc,
)
from .temple_parser import (
    parse_temple_zz_emoji_entry,
    parse_temple_zz_emoji_exit,
    parse_temple_zz_emoji_target,
    parse_temple_zz_stock_entry,
    parse_temple_zz_stock_exit,
    parse_temple_zz_trim,
    parse_temple_rf_options,
    parse_temple_options_standard,
    parse_temple_zz_options_a,
    parse_temple_zz_options_b,
    parse_temple_zz_options_exp,
    parse_temple_tc_options_range,
    parse_temple_ts_options,
    parse_temple_options_exit,
    parse_temple_zz_structured_entry,
    parse_temple_zz_inline_role_entry,
    parse_temple_zz_swing_update,
    parse_temple_zz_standalone_targets,
    parse_temple_zz_structured_entry_no_targets,
    parse_temple_zz_single_line_entry,
)
from .abtrades_parser import (
    parse_abtrades_entry,
    parse_abtrades_trim,
    parse_abtrades_exit,
)
from .eagle_options_parser import (
    parse_eagle_mba_entry,
    parse_eagle_nina_entry,
    parse_eagle_options_exit,
)

__all__ = [
    'parse_option_signal',
    'parse_stock_signal',
    'SignalParser',
    'get_default_option_pattern',
    'get_default_stock_pattern',
    'FLEXIBLE_OPT_PATTERN',
    'DEFAULT_STK_PATTERN',
    'create_option_regex',
    'create_stock_regex',
    'validate_signal',
    'is_valid_symbol',
    'is_valid_strike',
    'is_valid_expiry',
    'is_valid_action',
    'check_ticker_filter',
    'is_spy_sniper_signal',
    'parse_spy_sniper_signal',
    'process_spy_sniper_message',
    'SpySniperSignal',
    'SpySniperSignalType',
    'SpySniperPositionTracker',
    'get_position_tracker',
    'format_as_bto',
    'format_as_stc',
    'parse_temple_zz_emoji_entry',
    'parse_temple_zz_emoji_exit',
    'parse_temple_zz_emoji_target',
    'parse_temple_zz_stock_entry',
    'parse_temple_zz_stock_exit',
    'parse_temple_zz_trim',
    'parse_temple_rf_options',
    'parse_temple_options_standard',
    'parse_temple_zz_options_a',
    'parse_temple_zz_options_b',
    'parse_temple_zz_options_exp',
    'parse_temple_tc_options_range',
    'parse_temple_ts_options',
    'parse_temple_options_exit',
    'parse_temple_zz_structured_entry',
    'parse_temple_zz_inline_role_entry',
    'parse_temple_zz_swing_update',
    'parse_temple_zz_standalone_targets',
    'parse_abtrades_entry',
    'parse_abtrades_trim',
    'parse_abtrades_exit',
    'parse_eagle_mba_entry',
    'parse_eagle_nina_entry',
    'parse_eagle_options_exit',
]
